### PR TITLE
Handle all URI::Error exceptions in AbsoluteUrls decorator

### LINKED ISSUE #65: [AbsoluteUrls] Handle URI::InvalidComponentError error
# Problem

We're currently [handling `URI::InvalidURIError` exceptions](https://github.com/everypolitician/scraped/blob/c2e9db21e2922d8d8053bf7fa763228a0373db79/lib/scraped/response/decorator/absolute_urls.rb#L24), but not `URI::InvalidComponentError` exceptions (and possibly others).

# Proposed solution

Handle all `URI::Error` exceptions, rather than specific subclasses.

# Acceptance criteria

I shouldn't get the following error when running the [denmark-folketing scraper](https://github.com/everypolitician-scrapers/denmark-folketing).

```
/Users/chris/.rbenv/versions/2.3.3/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge': unrecognised opaque part for mailtoURL: postformand@ft.dk%20/%20dfpksekr@ft.dk (URI::InvalidComponentError)
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `each'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `inject'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `join'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/2.3.0/uri/common.rb:265:in `join'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response/decorator/absolute_urls.rb:19:in `absolute_url'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response/decorator/absolute_urls.rb:11:in `block (2 levels) in body'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response/decorator/absolute_urls.rb:11:in `block in body'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response/decorator/absolute_urls.rb:9:in `tap'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response/decorator/absolute_urls.rb:9:in `body'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response/decorator.rb:10:in `decorated_response'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response_decorator.rb:15:in `block in response'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response_decorator.rb:9:in `each'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response_decorator.rb:9:in `reduce'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/response_decorator.rb:9:in `response'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/document.rb:35:in `response'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/scraped-c2e9db21e292/lib/scraped/html.rb:11:in `noko'
	from scraper.rb:116:in `box'
	from scraper.rb:90:in `block in <class:MemberPage>'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/field_serializer-0.3.0/lib/field_serializer.rb:26:in `block in to_h'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/field_serializer-0.3.0/lib/field_serializer.rb:25:in `map'
	from /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/field_serializer-0.3.0/lib/field_serializer.rb:25:in `to_h'
	from scraper.rb:135:in `block (2 levels) in <main>'
	from scraper.rb:133:in `each'
	from scraper.rb:133:in `block in <main>'
	from scraper.rb:132:in `each'
	from scraper.rb:132:in `<main>'
```

# Related issues

This was originally reported by @ondenman in https://github.com/everypolitician/scraped/issues/52#issuecomment-273100561 on a similar issue.

### PR DESCRIPTION
**Pull request by chrismytton**
Previously we were only handling `URI::InvalidURIError` exceptions in the AbsoluteUrls decorator, but there's also `URI::BadURIError` and `URI::InvalidComponentError`.

We have encountered quite a few `URI::InvalidComponentError` exceptions in scrapers on pages which have invalid `mailto:` links, and these weren't being handled by the decorator correctly.

This change alters the `rescue` clause to use `URI::Error` so that we can rescue from all of these types of error and return the original relative url untouched, rather than blowing up.

Fixes #65 

# Notes to reviewer

This change was originally done in https://github.com/everypolitician/scraped/pull/66 but the `check-fail.sh` script was failing, see https://github.com/everypolitician/scraped/pull/66#issuecomment-281114063 for more details.

### CODE REVIEW

**Comment by chrismytton** [comment]
Have just pushed a couple more commits to update the version and changelog.

**Comment by tmtmtmtm** [comment]
@chrismytton I suspect you want to resolve the conflicts before review…

**Review by tmtmtmtm — APPROVED** [review]

**Comment by tmtmtmtm** [comment]
@chrismytton  — Gah, I didn't notice at review, but AbsoluteUrls was renamed CleanUrls whilst this was in development, and this now has a very confusing CHANGELOG…

**Comment by chrismytton** [comment]
> @chrismytton  — Gah, I didn't notice at review, but AbsoluteUrls was renamed CleanUrls whilst this was in development, and this now has a very confusing CHANGELOG…

Oops, my bad! Have opened https://github.com/everypolitician/scraped/pull/89 to fix that.

**Pull request merged**
