### PR TITLE
Move HTML specific parts into Scraped::HTML class

### LINKED ISSUE #17: Move HTML specific bits into a ScrapedPage::HTML class
# Problem

At the moment we've got some HTML-specific bits in the `ScrapedPage` base class, which will be problematic when we start to use this with JSON/XML/PDF/CSV.

# Proposed solution

~~Move the HTML-specific bits into a `ScrapedPage::HTML` class that pages can then inherit from. This class can then also be the place to handle things such as normalizing the HTML (#10).~~ <- this is now being done in the `Scraped::Response::Decorator` classes that were added in #21.

### PR DESCRIPTION
**Pull request by chrismytton**
In the future we expect to have classes for scraping other content types, so we don't want the root class to have logic for specific content types in it.

Fixes #17

### CODE REVIEW

**Comment by chrismytton** [comment]
@tmtmtmtm 👀

**Review by tmtmtmtm — COMMENTED** [review]
👍  for what's actually here, but I suspect it'd be a good idea to make sure we keep the test suite up to date too…

**Comment by chrismytton** [comment]
> I suspect it'd be a good idea to make sure we keep the test suite up to date too…

Oops, yep good point! Have pushed some tests for the `Scraped::HTML` class in https://github.com/everypolitician/scraped/pull/29/commits/6a2f526262e691cf47ee78c7c24cb4b9fcf451cc. I've also pushed https://github.com/everypolitician/scraped/pull/29/commits/b2082715c526ef1764ec069f964e180814f6b28f to make the `noko` method private again as I'd accidentally made it public.

**Review by tmtmtmtm — APPROVED** [review]
LGTM!

**Pull request merged**
