### PR TITLE
Add response decorators to Scraped subclasses

### PR DESCRIPTION
**Pull request by chrismytton**
We have been finding that more often than not it's better to specify decorators at the class level. If you don't specify them at the class level then there's no guarantee that the correct/expected decorators will have been run on the response before its passed to the constructor of a `Scraped` subclass.

So now creating and using a decorator looks like this:

```ruby
class CustomHeader < Scraped::Response::Decorator
  def headers
    response.headers.merge('X-Greeting' => config[:greeting])
  end
end

class ExamplePage < Scraped::HTML
  decorator CustomHeader, greeting: 'Hello, world'
end
```

Part of https://github.com/everypolitician/scraped/issues/28

### CODE REVIEW

**Review by tmtmtmtm — COMMENTED** [review]
Woot! A few quick comments pending a proper review once you've tried it in anger:

1) I think you need a test case that shows using multiple decorators.

2) Probably need to explain/show (docs + tests) whether decorators are inherited by subclasses (if they are, is there a way to un-decorate?) 

3) Simply saying 'decorator: X' is a little odd — it doesn't really convey the meaning well enough, I don't think, if you don't already understand deeply what's going on. I suspect something like `add_decorator: X` might be better, but perhaps we want go even further, with something like `preprocess_with: X`, or something along those lines?

**Comment by chrismytton** [comment]
> Probably need to explain/show (docs + tests) whether decorators are inherited by subclasses (if they are, is there a way to un-decorate?)

I've opened https://github.com/everypolitician/scraped/issues/35 as a speculative ticket about un-decorating in sub-classes. I'm not _entirely_ convinced that it's something we want to be doing, but we can discuss it further on that ticket.

**Comment by chrismytton** [comment]
I've added some more docs and tests to this, so I think it's ready for another review.

@everypolitician/team 👀

**Review by tmtmtmtm — APPROVED** [review]
LGTM!

**Pull request merged**
